import {
  CheckboxQuestion,
  Question,
  RadioQuestion,
  SelectQuestion,
} from "./question.model";

export const QUESTIONS_FOR_LAPTOP: Question[] = [
  new SelectQuestion("brand", "Бренд", [
    "Acer",
    "Apple",
    "ASUS",
    "Dell",
    "Gigabyte",
    "HP",
    "Huawei",
    "Lenovo",
    "Microsoft",
    "MSI",
    "Samsung",
    "Xiaomi",
  ]),
  new RadioQuestion("ram", "Обсяг оперативної пам'яті", [
    "<= 3 ГБ",
    "4 Гб",
    "6 Гб",
    "8 Гб",
    "10 Гб",
    "12 Гб",
    "16 Гб",
    "18 Гб",
    "24 Гб",
    "32 Гб",
  ]),
  new CheckboxQuestion("screenSize", "Розмір екрану", [
    `<13"`,
    `13"`,
    `14"`,
    `15"`,
    `16"`,
    `17"`,
    `18"`,
    `>18"`,
  ]),
  new SelectQuestion("processor", "Процесор", [
    "Intel Core i7",
    "Intel Core i5",
    "Intel Core i3",
    "AMD Ryzen 7",
    "AMD Ryzen 5",
    "AMD Ryzen 3",
    "Intel Core i9",
    "AMD Ryzen 9",
    "Intel Core Ultra 5",
    "Intel Core Ultra 7",
    "Intel Core Ultra 9",
    "M4",
    "Intel Pentium",
    "AMD Athlon",
    "M2",
    "M3",
    "Intel Core 3",
    "Intel Core 5",
    "Intel Core 7",
    "Intel Celeron",
    "Intel N-series",
    "Intel Core 2 Duo",
    "Intel Core Duo",
    "Intel Pentium_",
    "Intel Core Solo",
    "AMD Phenom",
    "AMD Turion",
    "AMD Sempron",
    "AMD V",
    "AMD Neo",
    "nVidia Tegra",
  ]),
  new CheckboxQuestion("storage", "Обсяг накопичувача типу", [
    "120 ГБ",
    "128 ГБ",
    "250 ГБ",
    "256 ГБ",
    "480 ГБ",
    "500 ГБ",
    "512 ГБ",
    "525 ГБ",
    "600 ГБ",
    "620 ГБ",
    "640 ГБ",
    "730 ГБ",
    "750 ГБ",
    "768 ГБ",
    "960 ГБ",
    "1 ТБ",
    "2 ТБ",
  ]),
  new RadioQuestion("videoMemory", "Обсяг відеопам'яті", [
    "2 ГБ",
    "3 ГБ",
    "4 ГБ",
    "6 ГБ",
    "8 ГБ",
  ]),
  new SelectQuestion("refreshRate", "Частота оновлення екрану", [
    "60 Гц",
    "90 Гц ",
    "100 Гц",
    "120 Гц",
    "144 Гц",
    "165 Гц",
    "180 Гц",
    "240 Гц",
    "250 Гц",
    "300 Гц",
    "360 Гц",
    "480 Гц",
  ]),
  new CheckboxQuestion("cpuCores", "Кількість ядер процесора", [
    "4",
    "6",
    "8",
    "10",
    "12",
    "14",
  ]),
  new CheckboxQuestion("ramType", "Тип оперативної пам'яті", [
    "DDR3",
    "DDR4",
    "DDR5",
    "DDR6",
  ]),
  new SelectQuestion("videoCardType", "Тип відеокарти", [
    "GeForce RTX 2050",
    "GeForce RTX 3050",
    "GeForce RTX 4050",
    "GeForce RTX 4060",
    "GeForce RTX 4070",
    "GeForce RTX 4080",
    "GeForсe RTX 4090",
    "GeForce RTX 5070 Ti",
    "GeForce RTX 5080",
    "GeForce RTX 5090",
    "GeForce RTX 3060",
    "Intel ARC",
    "GeForce RTX 3080",
    "GeForce RTX 3070 Ti",
    "GeForce RTX 3050 Ti",
    "GeForce GTX 1650",
    "GeForce RTX 3080 Ti",
    "GeForce RTX 3500",
    "GeForce GTX 1650 Max-Q",
    "GeForce RTX 2060",
    "GeForce RTX 2060 Max-Q",
    "GeForce RTX 2070",
    "GeForce RTX 2070 Max-Q",
    "GeForce RTX 2070 Super",
    "GeForce RTX 2070 Super Max-Q",
    "GeForce RTX 2080",
    "GeForce RTX 2080 Max-Q",
    "GeForce RTX 2080 Super",
    "GeForce RTX 2080 Super Max-Q",
    "GeForce RTX 3070",
    "GeForce RTX 4050 Max-Q",
    "GeForce RTX 2000",
    "GeForce RTX 3050M",
    "GeForce RTX 3060 Max-Q",
  ]),
  new RadioQuestion("screenType", "Тип екрану", [
    "IPS",
    "OLED",
    "VA",
    "TN",
    "Liquid Retina",
    "Mini-LED",
  ]),
  new SelectQuestion("screenResolution", "Роздільна здатність екрану", [
    "2K QHD (Quad HD)",
    "4K UHD (Ultra HD)",
    "Full HD",
    "ЗК",
    "5K",
    "Менше Full HD",
  ]),
  new SelectQuestion("storageType", "Тип накопичувача", [
    "SSD",
    "SSD + HDD",
    "eMMC",
    "HDD",
    "Optane + HDD",
    "Optane + SSHD",
  ]),
  new SelectQuestion("batteryCapacity", "Ємність акумулятора", [
    "< 30",
    "30 — 50",
    "51 — 70",
    "71 — 90",
    "> 90",
  ]),
  new CheckboxQuestion("additionalFeatures", "Додаткові можливості", [
    "Ідентифікація відбитка пальця",
    "З 3G/4G/5G модулем",
    "З підсвіткою клавіатури",
    "З сенсорним екраном",
    "Зарядка від USB",
    "Порт Thunderbolt",
    "Протиударний корпус",
    "Підтримує під'єднання 2 моніторів",
    "З оптичним приводом",
    "Знімна батарея",
  ]),
];
