import {
  CheckboxQuestion,
  RadioQuestion,
  SelectQuestion,
  type Question,
} from "./question.model";

export const QUESTIONS_FOR_MONOBLOCK: Question[] = [
  new SelectQuestion("brand", "Бренд", [
    "Acer",
    "Apple",
    "ARTLINE",
    "ASUS",
    "Cobra",
    "Dell",
    "HP",
    "Lenovo",
    "MSI",
  ]),
  new SelectQuestion("videoCard", "Відеокарта", [
    "GeForce RTX 3060",
    "GeForce RTX 3060 Ti",
    "GeForce RTX 4060",
    "GeForce RTX 4060 Ti",
    "GeForce GTX 1050",
    "GeForce GTX 1050 Ti",
    "GeForce GTX 1060",
    "GeForce GTX 1070",
    "GeForce GTX 1650",
    "GeForce GTX 1650 Super",
    "GeForce RTX 2070",
    "GeForce GTX 1660",
    "GeForce GTX 1660 Super",
    "GeForce RTX 2080",
    "GeForce RTX 2080 Super",
    "GeForce RTX 3050",
    "GeForce RTX 3050 Ti",
    "Radeon RX Vega",
    "AMD Radeon RX 6600M",
    "AMD Radeon Vega",
    "GeForce RTX 4050",
    "Intel HD Graphics",
    "Radeon RX 6300M",
    "Radeon RX 6500 XT",
  ]),
  new SelectQuestion("processor", "Процесор", [
    "Intel Core i9",
    "Intel Core i7",
    "Intel Core i5",
    "Intel Core i3",
    "AMD Ryzen 3",
    "AMD Ryzen 5",
    "AMD Ryzen 7",
    "Intel Core 7",
    "Intel Pentium",
    "Intel Celeron",
    "AMD Athlon",
    "Apple M1",
    "Apple M3",
    "Apple M4",
    "Intel Core 3",
    "Intel Core 5",
    "Intel Core Ultra 5",
    "Intel Core Ultra 7",
    "Intel N-series",
    "Intel Processor 300",
  ]),
  new RadioQuestion("ram", "Обсяг оперативної пам'яті", [
    "<= 3 ГБ",
    "4 ГБ",
    "6 ГБ",
    "8 ГБ",
    "12 ГБ",
    "16 ГБ",
    "24 ГБ",
    "32 ГБ",
    "64 ГБ",
  ]),
  new CheckboxQuestion("storage", "Обсяг накопичувача", [
    "<= 480 ГБ",
    "500 ГБ",
    "512 ГБ",
    "1 ТБ",
    "3 ТБ",
    "120 ГБ",
    "128 ГБ",
    "240 ГБ",
    "250 ГБ",
    "256 ГБ",
    "480 ГБ",
    "500 ГБ",
    "960 ГБ",
    "2 ТБ",
  ]),
  new CheckboxQuestion("videoMemory", "Обсяг відеопам'яті", [
    "<= 1.2 ГБ",
    "2 ГБ",
    "3 ГБ",
    "4 ГБ",
    "6 ГБ",
    "8 ГБ",
    "12 ГБ",
    "16 ГБ",
  ]),
  new CheckboxQuestion("cpuCores", "Кількість ядер процесора", [
    "<= 4",
    "5",
    "6",
    "8",
    "10",
    "12",
    "14",
    "16",
    "20",
  ]),
  new RadioQuestion("ramType", "Тип оперативної пам'яті", [
    "DDR3",
    "DDR4",
    "DDR5",
  ]),
  new RadioQuestion("storageType", "Тип накопичувача", [
    "HDD",
    "SSD",
    "HDD + SSD",
  ]),
  new RadioQuestion("screenSize", "Розмір екрана", [
    `20"`,
    `21"`,
    `22"`,
    `23"`,
    `24"`,
    `27"`,
    `28"`,
    `30"`,
    `31"`,
    `34"`,
  ]),
  new CheckboxQuestion("wirelessInterface", "Бездротовий інтерфейс", [
    "Bluetooth",
    "Wi-Fi",
    "Без бездротового під'єднання",
  ]),
];
