import {
  CheckboxQuestion,
  Question,
  RadioQuestion,
  SelectQuestion,
} from "./question.model";

export const QUESTIONS_FOR_SMARTWATCH: Question[] = [
  new SelectQuestion("brand", "Бренд", [
    "Amazfit",
    "Apple",
    "Garmin",
    "Gelius",
    "Google",
    "Honor",
    "Huawei",
    "Lemfo",
    "Lexego",
    "Samsung",
    "Smart Watch",
    "Xiaomi",
  ]),
  new RadioQuestion("os", "Операційна система", [
    "Android Wear OS",
    "Watch OS OS",
    "Tizen OS",
    "Інша OS",
    "Nucleus OS OS",
    "Garmin OS",
    "Harmony OS OS",
    "MicroOS OS",
    "LinkIt OS",
    "Elari OS OS",
  ]),
  new RadioQuestion("compatibility", "Сумісність з операційною системою", [
    "Android",
    "iOS",
  ]),
  new RadioQuestion("internalMemory", "Вбудована пам'ять", ["< 2Гб", "<= 2Гб"]),
  new SelectQuestion("screenSize", "Розмір екрану", [
    `< 1.5"`,
    `1.5" - 1.62"`,
    `> 1.62"`,
  ]),
  new CheckboxQuestion("wirelessTech", "Бездротова технологія", [
    "Bluetooth",
    "Wi-Fi",
    "NFC",
    "ANT+",
  ]),
  new CheckboxQuestion("sensors", "Датчики", [
    "Акселерометр",
    "Лічильник калорій",
    "Крокомір",
    "Пульсометр",
    "Знімання з руки",
    "Швидкість руху",
    "Вміст кисню в крові",
    "Гіроскоп",
    "З барометром",
    "З термометром",
    "Лічильник биття серця",
    "Тонометр",
    "Глибиномір",
  ]),
  new SelectQuestion("watchShape", "Форма годинника", [
    "Кругла",
    "Прямокутна",
    "Квадратна",
  ]),
  new SelectQuestion("chargingType", "Тип заряджання", [
    "Бездротова",
    "Магнітна",
    "Дротова",
  ]),
];
