import {
  CheckboxQuestion,
  RadioQuestion,
  SelectQuestion,
  type Question,
} from "./question.model";

export const QUESTIONS_FOR_SMARTPHONE: Question[] = [
  new SelectQuestion("brand", "Бренд", [
    "Apple",
    "HMD",
    "Infinix",
    "Motorola",
    "Nubia",
    "Poco",
    "realme",
    "Samsung",
    "Sigma mobile",
    "Tecno",
    "Ulefone",
    "Xiaomi",
  ]),
  new SelectQuestion("screenSize", "Розмір екрану", [
    `<= 4.59"`,
    `4.6" - 5"`,
    `5.01" - 5.5"`,
    `5.55" - 6"`,
    `6.01" - 6.49"`,
    `6.5" - 6.9"`,
    `>= 7"`,
  ]),
  new RadioQuestion("ram", "Обсяг оперативної пам'яті", [
    "2 ГБ",
    "3 ГБ",
    "4 ГБ",
    "6 ГБ",
    "8 ГБ",
    "12 ГБ",
    "16 ГБ",
    "18 ГБ",
    "24 ГБ",
    "32 ГБ",
  ]),
  new CheckboxQuestion("storage", "Обсяг вбудованої пам'яті", [
    "8 ГБ",
    "16 ГБ",
    "32 ГБ",
    "64 ГБ",
    "128 ГБ",
    "256 ГБ",
    "512 ГБ",
    "1 ТБ",
  ]),
  new SelectQuestion("batteryCapacity", "Ємність акумулятора", [
    "< 3000 мА*год",
    "3000 - 3999",
    "4000 - 4999 мА*год",
    "5000 - 5999 мА*год",
    ">= 6000 мА*год",
  ]),
  new CheckboxQuestion("wirelessTech", "Бездротові технології", [
    "Bluetooth",
    "NFC",
    "Wi-Fi",
    "Бездротова зарядка",
  ]),
  new SelectQuestion("mainCamera", "Основна камера", [
    "<= 15 Мп",
    "16 - 20.7 Мп",
    "21 - 48 Мп",
    "49 - 64 Мп",
    ">= 100 Мп",
  ]),
  new SelectQuestion("frontCamera", "Фронтальна камера", [
    "<= 8 Мп",
    "9 - 16 Мп",
    "17 - 20 Мп",
    "21 - 30 Мп",
    "31 - 39 Мп",
    ">= 40 Мп",
  ]),
  new SelectQuestion("processor", "Процесор", [
    "Apple",
    "MediaTek",
    "Qualcomm Snapdragon",
    "Samsung Exynos",
    "Unisoc",
    "HiSilicon Kirin",
    "Intel",
    "Spreadtrum",
  ]),
  new RadioQuestion("screenResolution", "Роздільна здатність екрана", [
    "WQHD (2560х1440)",
    "Full HD (1920x1080)",
    "4K UHD (3840x2160)",
    "HD (1280x720)",
  ]),
  new RadioQuestion("screenType", "Тип матриці", [
    "AMOLED",
    "Super AMOLED",
    "Dynamic AMOLED",
    "IPS",
    "LCD",
    "LTPS",
    "OLED",
    "PLS",
    "TFT",
    "TN",
  ]),
  new RadioQuestion("refreshRate", "Частота оновлення екрана", [
    "60 Гц",
    "90 Гц",
    "120 Гц",
    "144 Гц",
    "165 Гц",
    "185 Гц",
    "240 Гц",
  ]),
  new CheckboxQuestion("networkStandard", "Стандарт мобільного зв'язку", [
    "2G",
    "3G",
    "4G",
    "5G",
  ]),
  new RadioQuestion("os", "Операційна система", ["Android", "iOS"]),
  new RadioQuestion("simCards", "Кількість сім-карт", ["1", "2", "3", "4"]),
  new CheckboxQuestion("biometricSensor", "Тип біометричного сенсора", [
    "Сканер відбитків пальців",
    "Сканер сітківки",
    "Сканер обличчя",
  ]),
];
